on:
  push:
    tags:
      - v*

jobs:
  publish-github-package:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com

    - name: Install dependencies
      run: npm ci
    
    - name: Publish to GitHub Packages
      run: npm publish
  
  upload-module-to-google-bucket:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Google Authentication
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SA_EMAIL }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build standalone module with rollup
      run: npm run build
    
    - name: Upload module to bucket
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: output/bundle.mjs
        destination: alerts-streamer-service-bucket/alerts-js