on:
  push:
    tags:
      - v*

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SA_EMAIL }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Bundle everything
      run: |
        npm install
        npm run build
    
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'output/bundle.mjs'
        destination: 'alerts-streamer-service-bucket/alerts-js'